### PR TITLE
Added Example

### PR DESCRIPTION
**Pull request by miketamis**
Give this one a good think, we can definitely change this in the future but the less we change it the better.

### CODE REVIEW

**Comment by Jtmaca9** [comment]
Do we want a field for the component type, to future proof? Like JSX, or svelte

**Comment by Jtmaca9** [comment]
Also maybe title should be at the top level? to make it quicker at a glance to see which component the file is for

**Comment by miketamis** [comment]
We could flatten the whole info, and align that part more with a package. and only align on swagger for the props

**Comment by Jtmaca9** [comment]
Yeah I think that would be good!

**Comment by miketamis** [comment]
https://github.com/Jtmaca9/Component-Engine/pull/6/commits/67f1e17786ab420024fd0051370e3cd3fbfafd7c ?

**Pull request closed without merging**
